In [6]:
import numpy as np

data = np.array([[ 0.226, -0.23 , -0.86],[ 0.5639, 0.2379, 0.904]])
data

array([[ 0.226 , -0.23  , -0.86  ],
       [ 0.5639,  0.2379,  0.904 ]])

In [5]:
np.array([1, 2, 3], dtype=complex)
#我們可以提供我們要的資料類型給它，只需要在括號內加上dtype=資料類型

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
#創建資料的方法，也可以先建立一個list：
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data1)
arr1
#一維

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2
#二維

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
#要如何看資料(ndarray)有多少維？
print(arr2.ndim)
#若是想看是幾乘幾的矩陣可以使用shape
print(arr2.shape)
#看資料類型
data.dtype

2
(2, 4)


dtype('float64')

In [34]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]


array([5, 6, 7])

In [36]:
arr = np.arange(10)
arr[5:9] = 7
arr

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 9])

In [ ]:
myarr = np.arange(10)
slice = myarr[5:8]
myarr[5:8] = 7
slice[1] = 87
myarr
#第一行：建立的一個範圍0-9的資料
#第二行：將5、6、7改為數字7
#第三行：建立一個變數slice，內容為myarr[5:8]，也就是[7,7,7]
#第四行：改變slice第1個索引為87
#第五行：輸出myarr

In [37]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,2,2])
a * b


array([2, 4, 6])

In [45]:
#廣播
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
(xx + y)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [54]:
x = np.array([[3,4],[5,6],[7,8]])
x
x.T

array([[3, 5, 7],
       [4, 6, 8]])

In [58]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
(xx + y)

print(xx.base is x)
#在上面第二行，將x.reshape(4,1)得到的結果給了xx，這表示xx是從x來的，所以True
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
(xx + y)

print(xx.base is y)

True
False


In [60]:
import numpy as np
np.random.randn()#隨機數正負都有可能
np.random. randn(4,2) + 1.920929 #隨機創建一個4*2的矩陣,在加1.920929

array([[1.91959527, 2.23724357],
       [1.30446088, 2.7180332 ],
       [1.60127937, 2.97750089],
       [2.25414499, 2.37334609]])

In [62]:
np.random.randint(4, size=10)#產生<4的整數，總共為10
np.random.randint(low=4,high=10,size=10)#4~9的整數,共10個

array([8, 7, 5, 9, 9, 9, 5, 7, 7, 5])

In [64]:
x = np.random.randn(5, 4)
x.mean()
print(x)

[[ 1.41516231 -0.04300715  0.54259515 -0.62414202]
 [-0.2775085   1.33740035  1.0785215  -0.02813923]
 [ 0.18610201 -0.18806802 -0.24334297 -1.29146208]
 [ 0.26808542  0.60682826 -0.25085404 -1.66500661]
 [-0.38476211  0.20311731  1.63241245  0.5403835 ]]


In [67]:
x = np.array([[2,3,4], [5,6,7]])
np.cumsum(x)
#第一個index為2 = 2
#第二個index為2+3 = 5
#第三個index為2+3+4 = 9
#第四個index為2+3+4+5 = 14
#以此類推 。

array([10, 20, 30, 40])

In [69]:
#標準差
#std = sqrt(mean(abs(x - x.mean())**2))
x = np.array([[1, 2], [3, 4]])
np.std(x)

1.118033988749895

In [3]:
#建立一筆資料
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('my_array', x)

In [9]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np
aData = [1,2,3,4,5,6]
bData = [7,8,9,10,11,12]
np.savez('my_archive.npz', a=aData, b=bData)
myArch = np.load('my_archive.npz')


array([1, 2, 3, 4, 5, 6])

In [6]:
myArch['b']


array([ 7,  8,  9, 10, 11, 12])

In [7]:
myArch['a']


array([1, 2, 3, 4, 5, 6])

In [10]:
np.random.randn(6,4)

array([[-0.08923012, -1.68167578, -0.44681215, -0.78572481],
       [-0.5831975 ,  0.88301596,  0.86475339,  0.30881463],
       [-0.32274002, -1.43617704, -0.03353458,  0.77826671],
       [ 0.53803138,  0.68857979,  0.01765591, -0.51741059],
       [ 0.35629233,  1.38666324,  1.80179037,  0.01933119],
       [ 1.3174115 , -0.43360873,  0.85929015, -1.46845138]])