<a href="https://colab.research.google.com/github/GaryPython/30-day-for-python/blob/main/%E4%BD%9C%E6%A5%ADD07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [2]:
import numpy as np

In [5]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

In [22]:
array1_inv = np.linalg.inv(array1)
#反矩陣

In [23]:
np.transpose(array1)
#轉置

array([[10,  3],
       [ 8,  5]])

In [24]:
np.dot(array1_inv, array1)

array([[ 1.00000000e+00, -5.55111512e-17],
       [-1.11022302e-16,  1.00000000e+00]])

In [14]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print("特徵值",w,"\n特徵向量\n",v)

特徵值 [13.  2.] 
特徵向量
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [ ]:
#3. 運用上列array計算SVD?

In [19]:
u, s, vh = np.linalg.svd(array1)
print("u\n",u,"\ns\n",s,"\nvh\n",vh)

u
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
s
 [13.94721714  1.86417116] 
vh
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
